;;; parinfer-rust-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from parinfer-rust-changes.el

(register-definition-prefixes "parinfer-rust-changes" '("parinfer-rust--"))


;;; Generated autoloads from parinfer-rust-helper.el

(register-definition-prefixes "parinfer-rust-helper" '("parinfer-rust-"))


;;; Generated autoloads from parinfer-rust-mode.el

(autoload 'parinfer-rust-switch-mode "parinfer-rust-mode" "\
Switch to a different Parinfer mode.

Either: indent, smart, or paren." t)
(autoload 'parinfer-rust-toggle-paren-mode "parinfer-rust-mode" "\
Switch to paren mode if current mode is either smart or indent.
Switch back to previous mode if current mode is paren mode. Uses
`parinfer-rust-preferred-mode' as a fallback if previous mode is
not available." t)
(defvar parinfer-rust-mode-map (make-sparse-keymap) "\
Keymap for `parinfer-rust-mode'.")
(autoload 'parinfer-rust-mode "parinfer-rust-mode" "\
A simpler way to write lisps.

This is a minor mode.  If called interactively, toggle the
`Parinfer-Rust mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `parinfer-rust-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "parinfer-rust-mode" '("parinfer-rust-"))

;;; End of scraped data

(provide 'parinfer-rust-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; parinfer-rust-mode-autoloads.el ends here
