;;; hotfuzz-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from hotfuzz.el

(autoload 'hotfuzz-all-completions "hotfuzz" "\
Get hotfuzz-completions of STRING in TABLE.
See `completion-all-completions' for the semantics of PRED and POINT.
This function prematurely sorts the completions; mutating the returned
list before passing it to `display-sort-function' or
`cycle-sort-function' will lead to inaccuracies.

(fn STRING TABLE &optional PRED POINT)")
(autoload 'hotfuzz--adjust-metadata "hotfuzz" "\
Adjust completion METADATA for hotfuzz sorting.

(fn METADATA)")
(put 'hotfuzz 'completion--adjust-metadata #'hotfuzz--adjust-metadata)
(add-to-list 'completion-styles-alist '(hotfuzz completion-flex-try-completion hotfuzz-all-completions "Fuzzy completion."))
(define-obsolete-function-alias 'hotfuzz-vertico-mode #'ignore "0.1")
(register-definition-prefixes "hotfuzz" '("hotfuzz-"))

;;; End of scraped data

(provide 'hotfuzz-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; hotfuzz-autoloads.el ends here
